name: Build PexNPC
on: [ push, pull_request ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Set up JDK 21
        uses: actions/setup-java@v4.6.0
        with:
          java-version: 21.0.5
          distribution: 'temurin'
      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "Github Actions"
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build
        run: ./gradlew build
      - name: Upload Jar
        uses: actions/upload-artifact@v4.6.0
        with:
          name: PexNPC
          path: build/libs/PexNPC-2.0.jar